# permissions for end users to edit adds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: add-editor-role
rules:
- apiGroups:
  - basic.calc.k8s
  resources:
  - adds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - basic.calc.k8s
  resources:
  - adds/status
  verbs:
  - get
