# permissions for end users to view adds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: add-viewer-role
rules:
- apiGroups:
  - basic.calc.k8s
  resources:
  - adds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - basic.calc.k8s
  resources:
  - adds/status
  verbs:
  - get
