# permissions for end users to view divs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: div-viewer-role
rules:
- apiGroups:
  - basic.calc.k8s
  resources:
  - divs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - basic.calc.k8s
  resources:
  - divs/status
  verbs:
  - get
