# permissions for end users to edit muls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mul-editor-role
rules:
- apiGroups:
  - basic.calc.k8s
  resources:
  - muls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - basic.calc.k8s
  resources:
  - muls/status
  verbs:
  - get
