# permissions for end users to view muls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mul-viewer-role
rules:
- apiGroups:
  - basic.calc.k8s
  resources:
  - muls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - basic.calc.k8s
  resources:
  - muls/status
  verbs:
  - get
