# permissions for end users to edit subs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subs-editor-role
rules:
- apiGroups:
  - basic.calc.k8s
  resources:
  - subs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - basic.calc.k8s
  resources:
  - subs/status
  verbs:
  - get
